import Head from 'next/head';
import Menubar from './Common/Menubar';
import Hero from './Common/Hero';
import Service from './Common/Service';
import Footer from './Common/Footer';
import CategoryImage from './HomePage/CategoryImage';
import ProductCarousel from './HomePage/ProductCarousel';
import ProductBanner from './HomePage/ProductBanner';
import ProductListCarousel from './HomePage/ProductListCarousel';




export default function Home() {
  return (
    <div className='ThemeTwo'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <Menubar></Menubar>
        <Hero></Hero>
        <Service></Service>
        <CategoryImage/>
        <ProductCarousel/>
        <ProductBanner/>
        <ProductListCarousel/>
        <Footer></Footer>

      </main>

    </div>
  )
}



