import React from 'react'
import Head from 'next/head'
import LandingEleven from '../../Components/LandingPage/LandingEleven/LandingEleven'

const index = () => {
  return (

   
    <div className='Landing__Eleven'>
      
      {/* <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Funnel Line</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="images/favicon.png" />

      </Head> */}



            <LandingEleven></LandingEleven>
        
        </div>
  )
}

export default index