import Head from "next/head";
import React, { useRef, useState, useEffect } from "react";
import { baseUrl } from "../../../constant/constant";
// Common CSS
import Header from "../../../Components/theme_1/Common/Header";
import MenuBar from "../../../Components/theme_1/Common/Menubar";
import Delivary from "../../../Components/theme_1/Common/Delivary";
import Footer from "../../../Components/theme_1/Common/Footer";
import SocialMedia from "../../../Components/theme_1/Common/SocialMedia";
import TinyFooter from "../../../Components/theme_1/Common/TinyFooter";
import ProductDescription from "../../../Components/theme_1/ProductDetails/ProductDescription";
const axios = require("axios");
import { useRouter } from "next/router";
import Cookies from 'js-cookie'
const index = ({data}) => {
  return (
    <>
      <Head>
        <title>Sales Solution Theme_1</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='frontend_asset/images/Logo.png' />
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' crossorigin />
        <link
          href='https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700;800&display=swap'
          rel='stylesheet'
        />
      </Head>
      <main>
        <Header></Header>
        <MenuBar/>
        <ProductDescription></ProductDescription>
        <Delivary></Delivary>
        <Footer></Footer>
        <SocialMedia></SocialMedia>
        <TinyFooter></TinyFooter>
      </main>
      <footer></footer>
    </>
  );
};

export default index;

